// Package freepublicapis_test provides tests for the client package.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.
package freepublicapis_test

import (
	"context"
	"errors"
	"net/http"
	"testing"

	"github.com/go-api-libs/freepublicapis/pkg/freepublicapis"
)

type testRoundTripper struct {
	rsp *http.Response
	err error
}

func (t *testRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {
	return t.rsp, t.err
}

func TestClient_Error(t *testing.T) {
	ctx := context.Background()

	c, err := freepublicapis.NewClient()
	if err != nil {
		t.Fatal(err)
	}

	t.Run("Do", func(t testing.T) {
		testErr := errors.New("test error")
		http.DefaultClient.Transport = &testRoundTripper{err: testErr}

		if _, err := c.GetRandom(ctx); err == nil {
			t.Fatal("expected error")
		} else if !errors.Is(err, testErr) {
			t.Fatalf("want: %v, got: %v", testErr, err)
		}
	})
}
