// Package freepublicapis provides types for the API.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.
package freepublicapis

import "net/url"

// APIInfo defines a model
type APIInfo struct {
	ID            int     `json:"id"`
	Emoji         string  `json:"emoji"`
	Title         string  `json:"title"`
	Description   string  `json:"description"`
	Documentation url.URL `json:"documentation"`
	Methods       int     `json:"methods"`
	Health        int     `json:"health"`
	Source        url.URL `json:"source"`
}
